### PR TITLE
Fix `File.exists?` deprecation warning. Use `File.exist?` instead

### PR DESCRIPTION
**Pull request by techeverri**
Fixes https://github.com/csquared/IMGKit/issues/127

### CODE REVIEW

**Comment by techeverri** [comment]
Also closes https://github.com/csquared/IMGKit/pull/126

**Comment by brunohq** [comment]
+1

**Comment by nicolrx** [comment]
Hello @techeverri @csquared, is it possible de merge this pull request? Or, is there another version I can use somewhere that fixes the File.exists? deprecation issue? Thanks.

**Comment by priscilla-diff** [comment]
Hello @techeverri @csquared, when can we expect this to be merged? TIA

**Comment by csquared** [comment]
1.6.3 has just been published! Thanks :)

**Pull request merged**
